name: monitoring_stack

network:
  brand_net:
    driver: bridge
services:
  prometheus:
    image: "prom/prometheus:latest"
    volumes:
      - type: bind
      - source: ${PROM_PATH_SOURCE}
      - target: ${PROM_PATH_TARGET}
    ports:
      - "PROM_HOST_PORT:PROM_CONT_PORT"
    restart: unless-stopped
  grafana:
    image: "grafana/grafana:latest"
    volumes:
      - type: bind
      - source: ${GRAFANA_PATH_SOURCE}
      - target: ${GRAFANA_PATH_TARGET}
    ports:
      - ${GRAFANA_HOST_PORT}:${GRAFANA_CONT_PORT}
    depends_on:
      - prometheus
    restart: unless-stopped
  alertmanager:
    image: "prom/alertmanager:latest"
    volumes:
      - type: bind
      - source: ${AM_PATH_SOURCE}
      - target: ${AM_PATH_TARGET}
    command:
      - "--config.file=${AM_PATH_TARGET}"
    ports:
      - ${AM_HOST_PORT}:${AM_CONT_PORT}
    depends_on:
    - prometheus
