name: monitoring_stack

services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - type: bind
      - source: /etc/prometheus/prometheus.yml
      - target: /etc/prometheus/prometheus.yml

    ports:
      - "127.0.0.1:9090"
