groups:¬
- name: example-alerts¬
  rules:¬
  - alert: InstanceDown¬
    expr: up == 0¬
    for: 1m¬
    labels:¬
      severity: critical¬
    annotations:¬
      summary: "Instance {{ $labels.instance }} is down"¬
      description: "No response from {{ $labels.instance }} for 1 minute"¬
