route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: discord
  routes:
    - matchers:
        - service="pi_server"
      receiver: discord
      routes:
        - matchers:
            - severity="critical"
          receiver: discord

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, cluster, service]

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url: '${WEBHOOK_URL}'
